### ISSUE TITLE
RSS Parser

### ISSUE THREAD

**Issue by allella** [codeforgreenville/UpstateEvents#16]
For organizations without an API-method (Meetup, Eventbrite, Facebook), or iCal we can use an RSS feed if they have one particular to their events.

Hopefully we don't have any RSS feeds because they'd have to be crafted with event data and they really aren't made for that purpose alone. So, RSS would be a last resort in most cases.

I see the OpenUpstate website has an iCal(endar) link too, so we shouldn't have to rely on their RSS. 

I've added their iCal link to the speadsheet.

**Comment by smoking-peanuts** [comment]
Do you think that we should start asking people as of today.. Or do you think that we should build something with the orginizations that are using api and then once we have a working service we inform these groups how join?

**Comment by allella** [comment]
@smoking-peanuts I'd vote for waiting until we have something to show and give them a reason to want to care.

**Comment by smoking-peanuts** [comment]
Nice.. I agree.  Would you like me to help with everthing else because I have most of the contact that I am able to.. Some of the eventbrights are hard to find or search for so I will simply email the one's that I don't have

**Comment by allella** [comment]
Next step would be to double-check all the ones that we don't have listed as an API or iCal.

For example, I know Ta5 uses Eventbrite now, so we can add an API key for them.
http://www.eventbrite.com/e/287-tech-after-five-greenville-sc-january-21-2015-tickets-14981613409
