### ISSUE TITLE
Setup a data.codeforgreenville.org subdomain 

### ISSUE THREAD

**Issue by allella** [codeforgreenville/UpstateEvents#21]

**Comment by agautsc** [comment]
I've asked Wryen if we can transfer ownership of codeforgreenville.org

**Comment by agautsc** [comment]
I've reached out to Wryen a couple times with no response. If anyone else knows of a good non-email way to get ahold of him please reach out to him.

**Comment by allella** [comment]
Worst case, it expires on 2016-03-31T18:41:23Z and we can try to scoop it
up.

**Comment by allella** [comment]
The domain is in transfer from the registrar. Thanks to Wryen for transferring.

**Comment by allella** [comment]
Domain transferred. Closing.
