### ISSUE TITLE
Collect a list of existing public / open data sets

### ISSUE THREAD

**Issue by allella** [codeforgreenville/UpstateEvents#22]

**Comment by allella** [comment]
Let's start putting data here and we'll eventually move it to the data.codeforgreenville.org after the initial info is gathered

https://docs.google.com/spreadsheets/d/1IWsFT1p0ZY-DInfMOFq_gmqpGuKyl5wyBb9VoyoEjRs/edit#gid=0

**Comment by allella** [comment]
Some conversation happened over at
http://www.meetup.com/Upstate-Code-for-America/events/225887101/comments/456427616/?a=uc1_rd&read=1&_af=event&_af_eid=225887101&https=off

**Comment by nullvariable** [comment]
I added/updated the crime data for the county, it's a JSON post object and copying it to Postman got me a dump of the raw JSON that's being sent back to the browser to be overlayed on Google Maps

**Comment by allella** [comment]
Thanks Doug

**Comment by allella** [comment]
This speadsheet is still active and can be edited via the link at
https://data.openupstate.org/contribute
